name: Daily Email
on:
  schedule:
    - cron: '0 11 * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install openai requests
      - env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          APP_PASS: ${{ secrets.APP_PASS }}
          CURRENT_INDEX: ${{ vars.CURRENT_INDEX }}
        run: python main.py
